DROP TABLE Sub_Categories CASCADE CONSTRAINTS;
DROP TABLE Main_Categories CASCADE CONSTRAINTS;
DROP TABLE Business_Attributes CASCADE CONSTRAINTS;
DROP TABLE Days_Open CASCADE CONSTRAINTS;
DROP TABLE Reviews CASCADE CONSTRAINTS;
DROP TABLE Businesses CASCADE CONSTRAINTS;
DROP TABLE Users CASCADE CONSTRAINTS;

DROP INDEX Days_Open_Index;
DROP INDEX Business_Index;
DROP INDEX Reviews_Index;